### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [Elsie19/twilight-prompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by Elsie19** [comment]
I can add a license today, but since I'm on vacation, the screenshot won't be on for a couple days

**Comment by unixorn** [comment]
No rush, vacations are important. Close this issue once you've added both and I'll PR it into the list, or you can make your own PR if you have a specific blurb you want to describe it.

**Comment by Elsie19** [comment]
ok done!
